services:
  - type: web
    name: waprep-tuition-portal
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn tuition.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DJANGO_SETTINGS_MODULE
        value: tuition.settings_production
      - key: DEBUG
        value: false
    healthCheckPath: /
    autoDeploy: true

databases:
  - name: waprep-tuition-db
    plan: free