from django.urls import path
from django.contrib import admin
from . import views

app_name = 'tuition'

urlpatterns = [
    path('', views.home, name='home'),
    path('admin/', admin.site.urls),

    path('login/payer/', views.payer_login, name='payer_login'),
    path('login/admin/', views.admin_login, name='admin_login'),
    path('logout/', views.logout_view, name='logout'),
    path('forgot-password/', views.forgot_password, name='forgot_password'),
    path('forgot-id/', views.forgot_id, name='forgot_id'),
    path('reset-password/<str:token>/', views.reset_password, name='reset_password'),
    path('students/', views.students, name='students'),
    path('students/add/', views.add_student, name='add_student'),
    path('students/delete/', views.delete_student, name='delete_student'),
    path('students/update/', views.update_student, name='update_student'),
    path('students/update-notes/', views.update_student_notes, name='update_student_notes'),
    path('payment/<int:student_id>/', views.payment, name='payment'),
    path('payment/process/', views.process_payment, name='process_payment'),
    path('payment/history/', views.payment_history, name='payment_history'),
    path('payment/receipt/<int:payment_id>/', views.download_receipt, name='download_receipt'),
    path('payment/detail/<int:payment_id>/', views.payment_detail, name='payment_detail'),
    path('admin/dashboard/', views.admin_dashboard, name='admin_dashboard'),
    path('admin/reports/', views.admin_reports, name='admin_reports'),
    path('payer/dashboard/', views.payer_dashboard, name='payer_dashboard'),
    path('payer/welcome/', views.payer_welcome, name='payer_welcome'),
    path('payer/add-student/', views.add_student_to_payer, name='add_student_to_payer'),
    path('students/add-payer/', views.add_payer_to_student, name='add_payer_to_student'),
    path('students/remove-payer/', views.remove_payer_from_student, name='remove_payer_from_student'),
    path('student/<int:student_id>/', views.student_profile, name='student_profile'),
    path('student/add-payer/', views.add_payer_to_student, name='add_payer_to_student'),
    path('student/remove-payer/', views.remove_payer_from_student, name='remove_payer_from_student'),
    path('request-account/', views.request_account_view, name='request_account'),
    path('payer/profile/', views.payer_profile_view, name='payer_profile'),
    path('payer/edit-profile/', views.edit_payer_profile, name='edit_payer_profile'),

    path('ask-question/', views.ask_question_view, name='ask_question'),
    path('add-payment-method/', views.add_payment_method, name='add_payment_method'),
    path('manage-payment-methods/', views.manage_payment_methods, name='manage_payment_methods'),
    path('complete-bank-verification/<str:payment_method_id>/', views.complete_bank_verification, name='complete_bank_verification'),
    path('remove-payment-method/<str:payment_method_id>/', views.remove_payment_method, name='remove_payment_method'),
    path('manage-billing/', views.manage_billing, name='manage_billing'),
    path('manage-billing/student/<int:student_id>/', views.student_months, name='student_months'),
    path('manage-billing/student/<int:student_id>/<str:month_key>/', views.monthly_bills, name='monthly_bills'),
    path('manage-billing/<int:student_id>/', views.student_bills, name='student_bills'),
    path('send-activation-email/<int:student_payer_id>/', views.send_activation_email, name='send_activation_email'),
    path('send-activation-reminders/', views.send_activation_reminders, name='send_activation_reminders'),
    path('activate-account/<int:user_id>/<str:temp_password>/', views.activate_account, name='activate_account'),
    path('activation-setup/', views.activation_setup, name='activation_setup'),
    path('inline-edit-student/', views.inline_edit_student_field, name='inline_edit_student_field'),
    path('inline-edit-payment-notes/', views.inline_edit_payment_notes, name='inline_edit_payment_notes'),
    path('create-superuser/', views.create_superuser_view, name='create_superuser'),
    path('webhook/stripe/', views.stripe_webhook, name='stripe_webhook'),
    path('health/', views.health_check, name='health_check'),
    path('monitoring/audit-summary/', views.audit_summary, name='audit_summary'),
    path('monitoring/security-events/', views.security_events, name='security_events'),
    path('mass-add-bills/', views.mass_add_bills, name='mass_add_bills'),
    path('mass-billing-actions/', views.mass_billing_actions, name='mass_billing_actions'),
]  