# Generated by Django 4.2.20 on 2025-05-09 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tuition', '0003_student_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='notes',
            field=models.TextField(blank=True, help_text="Accountant's notes about the student"),
        ),
    ]
