# Generated by Django 4.2.20 on 2025-05-29 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tuition', '0006_accountrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='contact_info',
            field=models.TextField(blank=True),
        ),
    ]
