# Generated by Django 4.2.20 on 2025-05-29 23:45

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tuition', '0007_user_contact_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='current_balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
    ]
