# Generated by Django 4.2.20 on 2025-05-30 00:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tuition', '0008_student_current_balance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Studentpayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship', models.CharField(choices=[('mother', 'Mother'), ('father', 'Father'), ('guardian', 'Guardian'), ('other', 'Other')], max_length=20)),
                ('is_primary', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-is_primary', 'relationship'],
            },
        ),
        migrations.RemoveField(
            model_name='student',
            name='parents',
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('payer', 'Payer'), ('accountant', 'Accountant')], max_length=20),
        ),
        migrations.DeleteModel(
            name='StudentParent',
        ),
        migrations.AddField(
            model_name='studentpayer',
            name='payer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studentpayer',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tuition.student'),
        ),
        migrations.AddField(
            model_name='student',
            name='payers',
            field=models.ManyToManyField(related_name='students', through='tuition.Studentpayer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='studentpayer',
            unique_together={('student', 'payer')},
        ),
    ]
