# Generated by Django 4.2.21 on 2025-06-04 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tuition', '0009_studentpayer_remove_student_parents_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='notes',
            field=models.TextField(blank=True, help_text="admin's notes about the student"),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('payer', 'Payer'), ('admin', 'Admin')], max_length=20),
        ),
    ]
