# Generated by Django 4.2.21 on 2025-06-06 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tuition', '0010_student_due_date_alter_student_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_id',
            field=models.CharField(max_length=30, null=True, unique=True),
        ),
    ]
