# Generated by Django 4.2.21 on 2025-06-13 17:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tuition', '0015_payment_bank_account_alter_payment_account_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='payers',
            field=models.ManyToManyField(related_name='students', through='tuition.StudentPayer', to=settings.AUTH_USER_MODEL),
        ),
    ]
