# Generated by Django 4.2.21 on 2025-06-20 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tuition', '0017_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='stripe_payment_method_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='stripe_payment_method_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='stripe_customer_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
