# Generated by Django 4.2.21 on 2025-06-24 22:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tuition', '0018_bankaccount_stripe_payment_method_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('breakdown_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_items', to='tuition.paymentbreakdown')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_items', to='tuition.payment')),
            ],
            options={
                'unique_together': {('payment', 'breakdown_item')},
            },
        ),
    ]
