# Generated by Django 4.2.21 on 2025-06-26 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tuition', '0019_paymentitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='address',
        ),
        migrations.RemoveField(
            model_name='user',
            name='contact_info',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone_number',
        ),
    ]
