# Generated by Django 4.2.21 on 2025-06-26 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tuition', '0020_remove_phone_address_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountrequest',
            name='contact_info',
        ),
        migrations.AddField(
            model_name='accountrequest',
            name='student_names',
            field=models.TextField(blank=True, help_text='Enter the names of all students you are responsible for'),
        ),
    ]
