# Generated by Django 4.2.21 on 2025-07-03 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tuition', '0023_passwordhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentbreakdown',
            name='show_in_payment_history',
            field=models.BooleanField(default=False, help_text="If checked and bill is paid, this will appear in the payer's payment history"),
        ),
    ]
