# Generated by Django 4.2.21 on 2025-01-XX XX:XX

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tuition', '0024_paymentbreakdown_show_in_payment_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payer',
            field=models.ForeignKey(
                null=True, 
                blank=True, 
                on_delete=django.db.models.deletion.CASCADE, 
                related_name='payments_made',
                to='tuition.user',
                help_text='The payer who made this payment'
            ),
        ),
    ] 