# Generated by Django 4.2.21 on 2025-07-10 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tuition', '0025_payment_payer'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(blank=True, help_text='Method used for payment (e.g., cash, check, credit card machine, other)', max_length=50, null=True),
        ),
    ]
