# Generated by Django 4.2.21 on 2025-07-10 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tuition', '0026_payment_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='notes',
            field=models.TextField(blank=True, help_text='Admin notes about this payment', null=True),
        ),
    ]
