# Generated by Django 4.2.21 on 2025-07-14 21:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tuition', '0027_payment_notes'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemHealth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('component', models.CharField(help_text='System component being monitored', max_length=100)),
                ('status', models.CharField(choices=[('HEALTHY', 'Healthy'), ('WARNING', 'Warning'), ('CRITICAL', 'Critical'), ('UNKNOWN', 'Unknown')], max_length=20)),
                ('message', models.TextField(blank=True)),
                ('metrics', models.JSONField(blank=True, default=dict, help_text='Performance metrics')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['timestamp'], name='tuition_sys_timesta_f7e969_idx'), models.Index(fields=['component'], name='tuition_sys_compone_699834_idx'), models.Index(fields=['status'], name='tuition_sys_status_fb2b20_idx')],
            },
        ),
        migrations.CreateModel(
            name='SecurityEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('event_type', models.CharField(choices=[('LOGIN_FAILURE', 'Login Failure'), ('UNAUTHORIZED_ACCESS', 'Unauthorized Access'), ('SUSPICIOUS_ACTIVITY', 'Suspicious Activity'), ('DATA_BREACH', 'Data Breach'), ('SYSTEM_COMPROMISE', 'System Compromise'), ('RATE_LIMIT_EXCEEDED', 'Rate Limit Exceeded')], max_length=50)),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], max_length=20)),
                ('description', models.TextField()),
                ('user_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_events', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['timestamp'], name='tuition_sec_timesta_bfc734_idx'), models.Index(fields=['event_type'], name='tuition_sec_event_t_66693e_idx'), models.Index(fields=['severity'], name='tuition_sec_severit_f7cf71_idx'), models.Index(fields=['resolved'], name='tuition_sec_resolve_75d0d3_idx')],
            },
        ),
        migrations.CreateModel(
            name='DataVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=50)),
                ('record_id', models.IntegerField()),
                ('version_number', models.PositiveIntegerField()),
                ('data_snapshot', models.JSONField(help_text='Complete snapshot of the record at this version')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-version_number'],
                'indexes': [models.Index(fields=['model_name', 'record_id'], name='tuition_dat_model_n_45cd15_idx'), models.Index(fields=['created_at'], name='tuition_dat_created_5fcc9b_idx')],
                'unique_together': {('model_name', 'record_id', 'version_number')},
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('action', models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('PASSWORD_CHANGE', 'Password Change'), ('PASSWORD_RESET', 'Password Reset'), ('ACCESS_DENIED', 'Access Denied'), ('DATA_EXPORT', 'Data Export'), ('BULK_UPDATE', 'Bulk Update')], max_length=20)),
                ('model_name', models.CharField(choices=[('Student', 'Student'), ('User', 'User'), ('StudentPayer', 'StudentPayer'), ('Payment', 'Payment'), ('PaymentBreakdown', 'PaymentBreakdown'), ('BankAccount', 'BankAccount'), ('Card', 'Card'), ('AccountRequest', 'AccountRequest')], max_length=50)),
                ('record_id', models.IntegerField(help_text='ID of the affected record')),
                ('user_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('field_name', models.CharField(blank=True, help_text='Name of the changed field', max_length=100)),
                ('old_value', models.TextField(blank=True, help_text='Previous value (truncated if too long)')),
                ('new_value', models.TextField(blank=True, help_text='New value (truncated if too long)')),
                ('description', models.TextField(blank=True, help_text='Human-readable description of the change')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional context data')),
                ('session_id', models.CharField(blank=True, max_length=100)),
                ('request_id', models.CharField(blank=True, help_text='Unique request identifier', max_length=100)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['timestamp'], name='tuition_aud_timesta_a429cc_idx'), models.Index(fields=['action'], name='tuition_aud_action_864ea6_idx'), models.Index(fields=['model_name'], name='tuition_aud_model_n_99a2a9_idx'), models.Index(fields=['user'], name='tuition_aud_user_id_abb4c0_idx'), models.Index(fields=['record_id'], name='tuition_aud_record__fb05fa_idx')],
            },
        ),
    ]
