# Generated by Django 4.2.21 on 2025-07-14 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tuition', '0028_systemhealth_securityevent_dataversion_auditlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='metadata',
            field=models.TextField(blank=True, default=dict, help_text='Additional context data'),
        ),
        migrations.AlterField(
            model_name='dataversion',
            name='data_snapshot',
            field=models.TextField(help_text='Complete snapshot of the record at this version'),
        ),
        migrations.AlterField(
            model_name='securityevent',
            name='metadata',
            field=models.TextField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='systemhealth',
            name='metrics',
            field=models.TextField(blank=True, default=dict, help_text='Performance metrics'),
        ),
    ]
