# Generated by Django 4.2.21 on 2025-07-17 22:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tuition', '0029_alter_auditlog_metadata_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentbreakdown',
            name='date_incurred',
            field=models.DateField(default=django.utils.timezone.now, help_text='The date when this bill was incurred (defaults to creation date)'),
        ),
        migrations.AddField(
            model_name='paymentbreakdown',
            name='late_date',
            field=models.DateField(blank=True, help_text='The date when this bill becomes late (defaults to last day of current month)', null=True),
        ),
    ]
