# Generated by Django 4.2.21 on 2025-07-21 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tuition', '0030_paymentbreakdown_date_incurred_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymentbreakdown',
            options={'ordering': ['-is_paid', 'due_date', 'created_at']},
        ),
        migrations.AlterField(
            model_name='paymentbreakdown',
            name='date_incurred',
            field=models.DateField(help_text='The date when this bill was incurred (defaults to creation date)'),
        ),
    ]
