# Generated by Django 4.2.21 on 2025-07-24 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tuition', '0031_alter_paymentbreakdown_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='two_factor_enabled',
            field=models.BooleanField(default=False, help_text='Whether 2FA is enabled for this user'),
        ),
        migrations.AddField(
            model_name='user',
            name='two_factor_setup_complete',
            field=models.BooleanField(default=False, help_text='Whether 2FA setup has been completed'),
        ),
    ]
