# Generated by Django 4.2.21 on 2025-07-24 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tuition', '0032_user_two_factor_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Phone number for SMS 2FA', max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='two_factor_method',
            field=models.CharField(choices=[('totp', 'TOTP'), ('sms', 'SMS')], default='totp', help_text='2FA method preference', max_length=10),
        ),
    ]
