# Generated by Django 4.2.21 on 2025-08-04 17:28

from django.db import migrations, models

def convert_grade_to_integer(apps, schema_editor):
    """
    Convert grade field from string to integer.
    Handle cases where grade might be non-numeric or empty.
    """
    Student = apps.get_model('tuition', 'Student')
    
    for student in Student.objects.all():
        try:
            # Try to convert the grade to integer
            if student.grade and student.grade.strip():
                student.grade = int(student.grade.strip())
            else:
                # Default to 1 if grade is empty or None
                student.grade = 1
        except (ValueError, TypeError):
            # If conversion fails, default to 1
            student.grade = 1
        student.save()

def convert_grade_to_string(apps, schema_editor):
    """
    Convert grade field back to string (for rollback).
    """
    Student = apps.get_model('tuition', 'Student')
    
    for student in Student.objects.all():
        student.grade = str(student.grade)
        student.save()

class Migration(migrations.Migration):

    dependencies = [
        ('tuition', '0034_remove_two_factor_fields'),
    ]

    operations = [
        # First, convert the data
        migrations.RunPython(convert_grade_to_integer, convert_grade_to_string),
        
        # Then, change the field type
        migrations.AlterField(
            model_name='student',
            name='grade',
            field=models.IntegerField(help_text="Student's grade level (e.g., 1, 2, 3, etc.)"),
        ),
    ] 