# Generated by Django 4.2.21 on 2025-08-12 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tuition', '0035_change_grade_to_integer'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='currency',
            field=models.CharField(default='USD', help_text='Currency code (e.g., USD, EUR)', max_length=3),
        ),
        migrations.AddField(
            model_name='payment',
            name='exchange_rate',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Exchange rate to USD', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='exchange_rate_date',
            field=models.DateTimeField(blank=True, help_text='Date when exchange rate was set', null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='original_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Original amount in original currency', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='original_currency',
            field=models.CharField(blank=True, help_text='Original currency code', max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='paymentbreakdown',
            name='currency',
            field=models.CharField(default='USD', help_text='Currency code (e.g., USD, EUR)', max_length=3),
        ),
        migrations.AddField(
            model_name='paymentitem',
            name='currency',
            field=models.CharField(default='USD', help_text='Currency code (e.g., USD, EUR)', max_length=3),
        ),
    ]
