# Generated by Django 4.2.21 on 2025-08-12 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tuition', '0036_payment_currency_payment_exchange_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentbreakdown',
            name='payment_status_override',
            field=models.CharField(choices=[('unpaid', 'Unpaid'), ('partially_paid', 'Partially Paid'), ('paid', 'Paid')], default='unpaid', help_text='Manual override for payment status (overrides automatic calculation)', max_length=20),
        ),
    ]
