# Generated by Django 4.2.21 on 2025-08-13 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tuition', '0037_paymentbreakdown_payment_status_override'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentbreakdown',
            name='payment_status_override',
            field=models.CharField(choices=[('unpaid', 'Unpaid'), ('paid', 'Paid')], default='unpaid', help_text='Manual override for payment status (overrides automatic calculation)', max_length=20),
        ),
    ]
