# Generated by Django 4.2.21 on 2025-08-13 22:07

from django.db import migrations


def update_partially_paid_bills(apps, schema_editor):
    """Update any existing bills with 'partially_paid' status to 'unpaid'"""
    PaymentBreakdown = apps.get_model('tuition', 'PaymentBreakdown')
    
    # Find all bills with 'partially_paid' status and update them to 'unpaid'
    partially_paid_bills = PaymentBreakdown.objects.filter(payment_status_override='partially_paid')
    count = partially_paid_bills.count()
    
    if count > 0:
        partially_paid_bills.update(payment_status_override='unpaid')
        print(f"Updated {count} bills from 'partially_paid' to 'unpaid' status")


def reverse_update_partially_paid_bills(apps, schema_editor):
    """Reverse migration - this would be complex to reverse, so we'll just pass"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('tuition', '0038_remove_partially_paid_option'),
    ]

    operations = [
        migrations.RunPython(update_partially_paid_bills, reverse_update_partially_paid_bills),
    ]
